# Title of the project
shortname: "Dimensional Reduction and Style Based Inverse Kinematics"
longname: "Dimensional Reduction and Style IK"

start: "October 2006"
end: "October 2007"

personnel:
- name: Carl Henrik Ek
  role: PhD student and Manchester RA
  url: http://cms.brookes.ac.uk/staff/CarlEk/
- name: Huma Lodhi
  role: Former Post-doctorate Researcher
  url: http://www.doc.ic.ac.uk/~hml/

sponsors:
- name: EU FP6 PASCAL Network of Excellence
  ref: EU FP6 PASCAL Network of Excellence
  title: EU FP6 PASCAL Network of Excellence
  url: http://www.pascal-network.org

collaborators:
- name: Prof. Philip Torr
  institute: Oxford Brookes
  url: http://cms.brookes.ac.uk/staff/PhilipTorr/

software:
- url: "local"
  name: fgplvm
  tagline: "FGPLVM Toolbox for large scale learning of GP-LVMs."
- url: "local"
  name: hgplvm
  tagline: "HGPLVM Toolbox for hierarchical learning of GP-LVMs."
- url: "local"
  name: mocap
  tagline: "Simple MATLAB utility toolbox for loading motion capture data sets."

publications:
"Lawrence:gplvmtut06"
  conference:"Lawrence:larger07","Lawrence:hgplvm07","Ek:pose07","Ek:ambiguity08","Urtasun:topology08"
"Lawrence:oxford06","Lawrence:google07"
