# Title of the project
shortname: "LFM"
longname: "Latent Force Models: Mechanistically Inspired Convolution Processes for Learning"

start: "October 2007"
end: "January 2012"

personnel:
- name: Mauricio Alvarez
  role: PhD student
  url: "https://sites.google.com/site/maalvarezl/"

sponsors:
- name: Google Faculty Research Award
  ref: "Machine Learning 2008"
  title: "Latent Force Models: Mechanistically Inspired Convolution Processes for Learning"
  url: "http://research.google.com/university/relations/fra_recipients.html"

collaborators:
- name: Dr David Luengo
  institute: Carlos III University in Madrid
  url: ""

software:
- url: "http://sheffieldml.github.io/gpsim"
  name: gpsim
  tagline: "GPSIM: Gaussian Process Modelling of Single Input Motif networks."
- url: "http://sheffieldml.github.io/multigp"
  name: multigp
  tagline: "MULTIGP: Modelling multiple outputs with Gaussian processes (will eventually supercede the gpsim toolbox)."

publications:
  conference: ["Alvarez:lfm09","Alvarez:convolved08"]
  related: ["Bouttou:lskm07"]
