# Title of the project
shortname: "TIGRE"
longname: "TIGRE: Transcription factor Inference through Gaussian process Reconstruction of Expression"

start: "October 2007"
end: "April 2011"

personnel:
- name: Michalis Titsias
  role: Post-doctoral research assistant
  url: "http://www.aueb.gr/users/mtitsias/"
- name: Mauricio Alvarez
  role: PhD student
  url: "https://sites.google.com/site/maalvarezl/"

sponsors:
- name: EPSRC
  ref: EP/F005687/1
  title: "Gaussian Processes for Systems Identification with Applications in Systems Biology"
  url: "http://gow.epsrc.ac.uk/NGBOViewGrant.aspx?GrantRef=EP/F005687/1"

collaborators:
- name: Dr Nick Monk
  institute: University of Nottingham
  url: "http://www.maths.nottingham.ac.uk/personal/nm/"
- name: Dr Johannes Jaeger
  institute: CRG
  url: "http://www.crg.es/johannes_jaeger"
- name: Dr Antti Honkela
  institute: Helsinki University of Technology (visitor and collaborator)
  url: "http://www.cis.hut.fi/ahonkela/"

software:
- url: "http://inverseprobability.com/gpsim/"
  name: gpsim
  tagline: "GPSIM: Gaussian Process Modelling of single input module motif networks."
- url: "http://sheffieldml.github.io/multigp"
  name: multigp
  tagline: "MULTIGP: Modelling multiple outputs with Gaussian processes (will eventually supercede the gpsim toolbox)."
- url: "http://sheffieldml.github.io/disimrank"
  name: disimrank
  tagline: "DISIMRANK: Ranking potential targets using a driven input single input model motif."

publications:
  journals: "Alvarez:computationally11","Honkela:modelbased10","Gao:latent08"
  books: "Lawrence:licsb10"
  chapters: "Lawrence:licsbintro10","Lawrence:licsbbayes10","Lawrence:licsbgp10","Titsias:mcmcgp11"
  conference: "Alvarez:efficient10","Alvarez:lfm09","Titsias:variational09","Alvarez:convolved08","Titsias:efficient08","Lawrence:transcriptionalGP06"
  related: "DellaGatta:direct08","Alon:systems06","Sanguinetti:chipdyno06","Sabatti:bayesian06","Sanguinetti:chipvar06","Nachman:inferring04"
