# Title of the project
shortname: "OpenDreamKit"
longname: "Open Digital Research Environment Toolkit for the Advancement of Mathematics"

start: "September 2015"
end: "September 2019"

personnel:
- name: Michael Croucher
  role: Co-investigator
  url: "http://www.walkingrandomly.com/"

sponsors:
- name: "H2020-EU.1.4.1.3."
  ref: "676541"
  title: "Open Digital Research Environment Toolkit for the Advancement of Mathematics"
  url: "http://cordis.europa.eu/project/rcn/198334_en.html"

collaborators:
- name: "Michael Kohlhase"
  institute: Jacobs University Bremen
  url: "http://www.citizenme.com/"
- name: "Florent Cayré"
  institute: Logilab
  url: "https://www.logilab.fr/"
- name: "Hans Petter Langtangen"
  institute: Simula Research Lab
  url: "https://www.simula.no/"
- name: "Wolfram Decker"
  institute: University of Kaiserslautern
  url: ""
- name: "Ursula Martin"
  institute: University of Oxford
  url: "http://www.ox.ac.uk/"
- name: "Marcin Kostur"
  institute: University of Silesia
  url: "http://english.us.edu.pl/"
- name: "Hans Fangohr"
  institute: University of Southampton
  url: "http://www.southampton.ac.uk/"
- name: "Steve Linton"
  institute: University of St Andrews
  url: "https://www.st-andrews.ac.uk/"
- name: "John E. Cremona"
  institute: University of Warwick
  url: "http://www2.warwick.ac.uk/"
- name: "Paul-Olivier Dehaye"
  institute: Universität Zurich
  url: "http://www.uzh.ch/index.html"
- name: "Nicolas M. Thiéry"
  institute: Université Paris-Sud
  url: "http://www.u-psud.fr/fr/index.html"
- name: Vincent Delecroix
  institute: Université de Bordeaux
  url: "https://www.u-bordeaux.fr/"
- name: Luca De Feo
  institute: "Université de Versailles – Saint-Quentin-en-Yvelines"
  url: "http://www.uvsq.fr/"

software: []


publications: []

