# Title of the project
shortname: "Sloppy"
longname: "Learning Classifiers from Sloppily Labelled Data"

start: "October 2005"
end: "October 2004"

personnel:
- name: Tonatiuh Peña-Centeno
  role: PhD Student
  url: T.Centeno

sponsors:
- name: EPSRC 
  ref: GR/R84801/01
  title: EPSRC Grant no GR/R84801/01
  url: http://gow.epsrc.ac.uk/NGBOViewGrant.aspx?GrantRef=GR/R84801/01

software:
- url: "http://inverseprobability.com/bfd"
  name: bfd
  tagline: "Bayesian interpretation of kernel Fisher's discriminants."
- url: "http://inverseprobability.com/ncnm"
  name: ncnm
  tagline: "Semi-supervised learning for Gaussian process classifiers."
- url: "http://inverseprobabiliity.com/ivm"
  name: ivm
  tagline: "Sparse approximation for Gaussian process classifiers."

publications:
  journals: "Pena:fbd04"
  conference: "Lawrence:ivm02","Lawrence:semisuper04","Lawrence:noisy01"
  chapters:"Lawrence:extensions05","Lawrence:gpncnm05"
  techreports: "Pena:fbd-tech04","Lawrence:ivmTech04"
