# Title of the project
shortname: "MLPM Project"
longname: "MLPM: Machine Learning for Personalized Medicine"

start: "January 2012"
end: "January 2015"

personnel:
- name: Max Zwiessele
  role: PhD Student
  url: M.Zwiessele
- name: James McMurray
  role: PhD Student
  url: J.McMurray
- name: James Hensman
  role: MRC Fellow
  url: J.Hensman

sponsors:
- name: EU FP7-PEOPLE Project Ref 316861 "MLPM2012: Machine Learning for Personalized Medicine"
  ref: EU FP7-PEOPLE Project Ref 316861 "MLPM2012: Machine Learning for Personalized Medicine"
  title: EU FP7-PEOPLE Project Ref 316861 "MLPM2012: Machine Learning for Personalized Medicine"
  url: http://cordis.europa.eu/projects/rcn/105442_en.html

collaborators:
- name: Magnus Rattray
  institute: University of Manchester
  url: http://www.ls.manchester.ac.uk/people/profile/?personid=10584
- name: Karsten Borgwardt
  institute: MPI for Intelligent Systems
  url: http://webdav.tuebingen.mpg.de/u/karsten/group/index.html
- name: Bernhard Schoelkopf
  institute: MPI for Intelligent Systems
  url: http://www.is.tuebingen.mpg.de/research/departments/bs.html
- name: Bertram Mueller-Myhsok
  institute: MPI for Psychiatry
  url: http://www.mpipsykl.mpg.de/en/research/groups/muellermyhsok/index.html
- name: Volker Tresp
  institute: Siemens AG
  url: http://www.siemens.com/
- name: Felix Agakov
  institute: Pharmatics LTD
  url: http://www.pharmaticsltd.com/
- name: Kristel Van Steen
  institute: Universit\'e de Li\`ege
  url: http://www.montefiore.ulg.ac.be/~kvansteen/
- name: Jean Philippe Vert
  institute: Mines ParisTech (Armines)
  url: http://cbio.ensmp.fr/~jvert/
- name: Florence Demenais
  institute: INSERM
  url: http://www.univ-paris-diderot.fr/IUH/pgeng.php?np=97
- name: Fernando Perez Cruz
  institute: Universidad Carlos III de Madrid
  url: http://www.tsc.uc3m.es/~fernando/
- name: Joaquin Dopazo
  institute: Principe Felipe Centro de Investigacion
  url: http://bioinfo.cipf.es/
- name: Gunnar Raetsch
  institute: Memorial Sloan-Kettering Cancer Center
  url: http://cbio.mskcc.org/research/ratsch-research-group/

software:
- url: "SheffieldML"
  name: GPy
  tagline: "GPy: Gaussian process modelling framework in Python"
- url: "SheffieldML"
  name: colvb
  tagline: "Collapsed Variational Bayes Software"
- url: "SheffieldML"
  name: TVB
  tagline: "Tilted variational inference software"

publications:
  conference:"Hensman:tvb14","Andrade:hybrid14"
  related:"Hensman:hierarchical13","Fusi:detecting13","Hensman:fast12","Hensman:bigdata13","Fusi:genomics12"
